function hexToRgb(hex) {
  var h = hex.replace('#', '');
  return {
    r: parseInt(h.substring(0, 2), 16) / 255,
    g: parseInt(h.substring(2, 4), 16) / 255,
    b: parseInt(h.substring(4, 6), 16) / 255
  };
}

function angleToTransform(angleDeg) {
  var rad = (angleDeg * Math.PI) / 180;
  var cos = Math.cos(rad);
  var sin = Math.sin(rad);
  return [
    [cos, sin, 0.5 - 0.5 * cos - 0.5 * sin],
    [-sin, cos, 0.5 + 0.5 * sin - 0.5 * cos]
  ];
}

function setProp(instance, prefix, value) {
  var props = instance.componentProperties;
  for (var key in props) {
    var propName = key.split('#')[0];
    if (propName === prefix) {
      instance.setProperties({ [key]: value });
      return;
    }
  }
}

function _fillH(n) {
  var p = n.parent; if (!p) return;
  if (p.layoutMode && p.layoutMode !== 'NONE') { n.layoutSizingHorizontal = 'FILL'; }
  else { n.resize(Math.max((p.width||0)-(p.paddingLeft||0)-(p.paddingRight||0),1), n.height); }
}
function _fillV(n) {
  var p = n.parent; if (!p) return;
  if (p.layoutMode && p.layoutMode !== 'NONE') { n.layoutSizingVertical = 'FILL'; }
  else { n.resize(n.width, Math.max((p.height||0)-(p.paddingTop||0)-(p.paddingBottom||0),1)); }
}


// Navigate to target page
var _targetNode = await figma.getNodeByIdAsync(undefined);
var _page = _targetNode;
while (_page && _page.type !== 'PAGE') _page = _page.parent;
if (_page) await figma.setCurrentPageAsync(_page);

// Load fonts
await Promise.all([
  figma.loadFontAsync({ family: 'Inter', style: 'Regular' }),
  figma.loadFontAsync({ family: 'Inter', style: 'Semi Bold' }),
  figma.loadFontAsync({ family: 'Inter', style: 'Bold' }),
  figma.loadFontAsync({ family: 'Inter', style: 'Medium' }),
  figma.loadFontAsync({ family: 'Fira Code', style: 'Regular' }),
  figma.loadFontAsync({ family: 'Roboto', style: 'Regular' }),
]);

// Import components
var _imp_genLog = await figma.importComponentByKeyAsync('a9653f30925367e96dea90093d750bfe70849571');
var _imp_divider = await figma.importComponentByKeyAsync('f4d778e1cf9bb61a33712c791486f54bb1c095b7');
var _imp_codeBlock = await figma.importComponentByKeyAsync('1bf10eee1751a46da5f90a9671be6c9abf0073b7');
var _imp_flowCoverCard = await figma.importComponentByKeyAsync('eaebde6bd07d2f19f3f9c00a9587240cb085a90d');
var _imp_researchFrame = await figma.importComponentByKeyAsync('e671618f2b4c6ea406a995fdc3012ac54eadfe56');
var _imp_feedback = await figma.importComponentSetByKeyAsync('d5cba21bc3dbf36578665bac89834fbe1ca29ed0');
var _imp_briefCard = await figma.importComponentSetByKeyAsync('3dbb732730af0754210cde7af35e5236a2502843');
var _imp_doDontPair = await figma.importComponentSetByKeyAsync('28edfacf13e50706586172bd48f8a3ad84d7c263');
var _imp_contrastBadge = await figma.importComponentSetByKeyAsync('941756541adc6ce21e32e848c2039c64fece0fcf');
var _imp_pointerBadge = await figma.importComponentSetByKeyAsync('7e066fc21d9a2bbbcd1149113787cf59140162d4');
var _imp_dimAnnotation = await figma.importComponentSetByKeyAsync('49bf6a1b210a403ba145a3fdee9b1994eb54069a');
var _imp_a11yCard = await figma.importComponentSetByKeyAsync('b4779a13f4097d682413a669eaaf9ead1b49f115');

// Load local components
var _local_targetComponent = await figma.importComponentSetByKeyAsync('675f7f8d0d57162e4cce51d26cbe39cf490e9b8d');

// Create or find wrapper
var _wrapper = await figma.getNodeByIdAsync('__WRAPPER_ID__');
if (!_wrapper) throw new Error('Wrapper __WRAPPER_ID__ not found');

// Build tree
var _nodeCount = 0;
var c0;
(function() {
  var _cs = _imp_briefCard;
  if (_cs.type === 'COMPONENT_SET') {
    var _variants = _cs.children;
    var _target = null;
    for (var _i = 0; _i < _variants.length; _i++) {
      if (_variants[_i].name === 'Mode=DS, Type=Standard') { _target = _variants[_i]; break; }
    }
    if (!_target) {
      for (var _j = 0; _j < _variants.length; _j++) {
        if (_variants[_j].name.indexOf('Mode=DS, Type=Standard') !== -1) { _target = _variants[_j]; break; }
      }
    }
    if (_target) {
      c0 = _target.createInstance();
    } else {
      c0 = (_cs.defaultVariant || _cs.children[0]).createInstance();
    }
  } else {
    c0 = _cs.createInstance();
  }
})();
c0.name = 'Design tokens';
c0.resize(1200, c0.height);
setProp(c0, 'Title', 'Design tokens');
setProp(c0, 'Subtitle', 'Color, sizing, spacing, and typography tokens');
c0 = c0.detachInstance();
var c0_slot = c0.findOne(function(n) { return n.name === "Content"; }) || c0;
if (c0_slot !== c0) {
  while (c0_slot.children.length) c0_slot.children[0].remove();
}
if (c0_slot !== c0) {
  c0_slot.layoutMode = 'VERTICAL';
  c0_slot.itemSpacing = 16;
  c0_slot.paddingTop = 48;
  c0_slot.paddingRight = 80;
  c0_slot.paddingBottom = 48;
  c0_slot.paddingLeft = 80;
  c0_slot.primaryAxisSizingMode = 'AUTO';
  c0_slot.counterAxisSizingMode = 'AUTO';
}
var c1 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Semi Bold' });
c1.fontName = { family: 'Inter', style: 'Semi Bold' };
c1.fontSize = 16;
c1.characters = 'Color tokens';
c1.fills = [{ type: 'SOLID', color: hexToRgb('#1A1A2E') }];
c0_slot.appendChild(c1);
var c2 = figma.createFrame();
c2.name = 'Color tokens table';
c2.layoutMode = 'VERTICAL';
c2.itemSpacing = 0;
c2.paddingTop = 0;
c2.paddingRight = 0;
c2.paddingBottom = 0;
c2.paddingLeft = 0;
c2.primaryAxisSizingMode = 'AUTO';
c2.counterAxisSizingMode = 'AUTO';
c2.fills = [];
var c3 = figma.createFrame();
c3.name = 'Header';
c3.layoutMode = 'HORIZONTAL';
c3.itemSpacing = 0;
c3.paddingTop = 8;
c3.paddingRight = 12;
c3.paddingBottom = 8;
c3.paddingLeft = 12;
c3.primaryAxisSizingMode = 'AUTO';
c3.counterAxisSizingMode = 'AUTO';
c3.fills = [{ type: 'SOLID', color: hexToRgb('#F5F5FA') }];
var c4 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Bold' });
c4.fontName = { family: 'Inter', style: 'Bold' };
c4.fontSize = 12;
c4.characters = 'Variant / State';
c4.fills = [{ type: 'SOLID', color: hexToRgb('#595968') }];
c4.resize(140, c4.height);
c4.textAutoResize = 'HEIGHT';
c3.appendChild(c4);
var c5 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Bold' });
c5.fontName = { family: 'Inter', style: 'Bold' };
c5.fontSize = 12;
c5.characters = 'Text';
c5.fills = [{ type: 'SOLID', color: hexToRgb('#595968') }];
c5.resize(160, c5.height);
c5.textAutoResize = 'HEIGHT';
c3.appendChild(c5);
var c6 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Bold' });
c6.fontName = { family: 'Inter', style: 'Bold' };
c6.fontSize = 12;
c6.characters = 'Icon';
c6.fills = [{ type: 'SOLID', color: hexToRgb('#595968') }];
c6.resize(160, c6.height);
c6.textAutoResize = 'HEIGHT';
c3.appendChild(c6);
var c7 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Bold' });
c7.fontName = { family: 'Inter', style: 'Bold' };
c7.fontSize = 12;
c7.characters = 'Underline';
c7.fills = [{ type: 'SOLID', color: hexToRgb('#595968') }];
c7.resize(160, c7.height);
c7.textAutoResize = 'HEIGHT';
c3.appendChild(c7);
c2.appendChild(c3);
_fillH(c3);
c3.layoutSizingVertical = 'HUG';
var c8 = figma.createFrame();
c8.name = 'Row 0';
c8.layoutMode = 'HORIZONTAL';
c8.itemSpacing = 0;
c8.paddingTop = 8;
c8.paddingRight = 12;
c8.paddingBottom = 8;
c8.paddingLeft = 12;
c8.primaryAxisSizingMode = 'AUTO';
c8.counterAxisSizingMode = 'AUTO';
c8.fills = [];
var c9 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Medium' });
c9.fontName = { family: 'Inter', style: 'Medium' };
c9.fontSize = 14;
c9.characters = 'Enabled';
c9.fills = [{ type: 'SOLID', color: hexToRgb('#1A1A2E') }];
c9.resize(140, c9.height);
c9.textAutoResize = 'HEIGHT';
c8.appendChild(c9);
var c10 = figma.createFrame();
c10.name = 'Cell: theme-primary';
c10.layoutMode = 'HORIZONTAL';
c10.itemSpacing = 6;
c10.paddingTop = 0;
c10.paddingRight = 0;
c10.paddingBottom = 0;
c10.paddingLeft = 0;
c10.primaryAxisSizingMode = 'AUTO';
c10.counterAxisSizingMode = 'AUTO';
c10.fills = [];
var c11 = figma.createEllipse();
c11.name = 'Swatch';
c11.resize(16, 16);
c11.fills = [{ type: 'SOLID', color: hexToRgb('#0550DC') }];
c10.appendChild(c11);
var c12 = figma.createText();
await figma.loadFontAsync({ family: 'Fira Code', style: 'Regular' });
c12.fontName = { family: 'Fira Code', style: 'Regular' };
c12.fontSize = 11;
c12.characters = 'theme-primary #0550DC';
c12.fills = [{ type: 'SOLID', color: hexToRgb('#595968') }];
c10.appendChild(c12);
c8.appendChild(c10);
c10.layoutSizingHorizontal = 'HUG';
c10.layoutSizingVertical = 'HUG';
var c13 = figma.createFrame();
c13.name = 'Cell: theme-primary';
c13.layoutMode = 'HORIZONTAL';
c13.itemSpacing = 6;
c13.paddingTop = 0;
c13.paddingRight = 0;
c13.paddingBottom = 0;
c13.paddingLeft = 0;
c13.primaryAxisSizingMode = 'AUTO';
c13.counterAxisSizingMode = 'AUTO';
c13.fills = [];
var c14 = figma.createEllipse();
c14.name = 'Swatch';
c14.resize(16, 16);
c14.fills = [{ type: 'SOLID', color: hexToRgb('#0550DC') }];
c13.appendChild(c14);
var c15 = figma.createText();
await figma.loadFontAsync({ family: 'Fira Code', style: 'Regular' });
c15.fontName = { family: 'Fira Code', style: 'Regular' };
c15.fontSize = 11;
c15.characters = 'theme-primary #0550DC';
c15.fills = [{ type: 'SOLID', color: hexToRgb('#595968') }];
c13.appendChild(c15);
c8.appendChild(c13);
c13.layoutSizingHorizontal = 'HUG';
c13.layoutSizingVertical = 'HUG';
var c16 = figma.createFrame();
c16.name = 'Cell: —';
c16.layoutMode = 'HORIZONTAL';
c16.itemSpacing = 6;
c16.paddingTop = 0;
c16.paddingRight = 0;
c16.paddingBottom = 0;
c16.paddingLeft = 0;
c16.primaryAxisSizingMode = 'AUTO';
c16.counterAxisSizingMode = 'AUTO';
c16.fills = [];
var c17 = figma.createEllipse();
c17.name = 'Swatch';
c17.resize(16, 16);
c17.fills = [];
c16.appendChild(c17);
var c18 = figma.createText();
await figma.loadFontAsync({ family: 'Fira Code', style: 'Regular' });
c18.fontName = { family: 'Fira Code', style: 'Regular' };
c18.fontSize = 11;
c18.characters = '— transparent';
c18.fills = [{ type: 'SOLID', color: hexToRgb('#595968') }];
c16.appendChild(c18);
c8.appendChild(c16);
c16.layoutSizingHorizontal = 'HUG';
c16.layoutSizingVertical = 'HUG';
c2.appendChild(c8);
_fillH(c8);
c8.layoutSizingVertical = 'HUG';
var c19 = figma.createFrame();
c19.name = 'Row 1';
c19.layoutMode = 'HORIZONTAL';
c19.itemSpacing = 0;
c19.paddingTop = 8;
c19.paddingRight = 12;
c19.paddingBottom = 8;
c19.paddingLeft = 12;
c19.primaryAxisSizingMode = 'AUTO';
c19.counterAxisSizingMode = 'AUTO';
c19.fills = [];
var c20 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Medium' });
c20.fontName = { family: 'Inter', style: 'Medium' };
c20.fontSize = 14;
c20.characters = 'Hovered';
c20.fills = [{ type: 'SOLID', color: hexToRgb('#1A1A2E') }];
c20.resize(140, c20.height);
c20.textAutoResize = 'HEIGHT';
c19.appendChild(c20);
var c21 = figma.createFrame();
c21.name = 'Cell: theme-primary-hover';
c21.layoutMode = 'HORIZONTAL';
c21.itemSpacing = 6;
c21.paddingTop = 0;
c21.paddingRight = 0;
c21.paddingBottom = 0;
c21.paddingLeft = 0;
c21.primaryAxisSizingMode = 'AUTO';
c21.counterAxisSizingMode = 'AUTO';
c21.fills = [];
var c22 = figma.createEllipse();
c22.name = 'Swatch';
c22.resize(16, 16);
c22.fills = [{ type: 'SOLID', color: hexToRgb('#0343B5') }];
c21.appendChild(c22);
var c23 = figma.createText();
await figma.loadFontAsync({ family: 'Fira Code', style: 'Regular' });
c23.fontName = { family: 'Fira Code', style: 'Regular' };
c23.fontSize = 11;
c23.characters = 'theme-primary-hover #0343B5';
c23.fills = [{ type: 'SOLID', color: hexToRgb('#595968') }];
c21.appendChild(c23);
c19.appendChild(c21);
c21.layoutSizingHorizontal = 'HUG';
c21.layoutSizingVertical = 'HUG';
var c24 = figma.createFrame();
c24.name = 'Cell: theme-primary-hover';
c24.layoutMode = 'HORIZONTAL';
c24.itemSpacing = 6;
c24.paddingTop = 0;
c24.paddingRight = 0;
c24.paddingBottom = 0;
c24.paddingLeft = 0;
c24.primaryAxisSizingMode = 'AUTO';
c24.counterAxisSizingMode = 'AUTO';
c24.fills = [];
var c25 = figma.createEllipse();
c25.name = 'Swatch';
c25.resize(16, 16);
c25.fills = [{ type: 'SOLID', color: hexToRgb('#0343B5') }];
c24.appendChild(c25);
var c26 = figma.createText();
await figma.loadFontAsync({ family: 'Fira Code', style: 'Regular' });
c26.fontName = { family: 'Fira Code', style: 'Regular' };
c26.fontSize = 11;
c26.characters = 'theme-primary-hover #0343B5';
c26.fills = [{ type: 'SOLID', color: hexToRgb('#595968') }];
c24.appendChild(c26);
c19.appendChild(c24);
c24.layoutSizingHorizontal = 'HUG';
c24.layoutSizingVertical = 'HUG';
var c27 = figma.createFrame();
c27.name = 'Cell: theme-primary-hover';
c27.layoutMode = 'HORIZONTAL';
c27.itemSpacing = 6;
c27.paddingTop = 0;
c27.paddingRight = 0;
c27.paddingBottom = 0;
c27.paddingLeft = 0;
c27.primaryAxisSizingMode = 'AUTO';
c27.counterAxisSizingMode = 'AUTO';
c27.fills = [];
var c28 = figma.createEllipse();
c28.name = 'Swatch';
c28.resize(16, 16);
c28.fills = [{ type: 'SOLID', color: hexToRgb('#0343B5') }];
c27.appendChild(c28);
var c29 = figma.createText();
await figma.loadFontAsync({ family: 'Fira Code', style: 'Regular' });
c29.fontName = { family: 'Fira Code', style: 'Regular' };
c29.fontSize = 11;
c29.characters = 'theme-primary-hover #0343B5';
c29.fills = [{ type: 'SOLID', color: hexToRgb('#595968') }];
c27.appendChild(c29);
c19.appendChild(c27);
c27.layoutSizingHorizontal = 'HUG';
c27.layoutSizingVertical = 'HUG';
c2.appendChild(c19);
_fillH(c19);
c19.layoutSizingVertical = 'HUG';
var c30 = figma.createFrame();
c30.name = 'Row 2';
c30.layoutMode = 'HORIZONTAL';
c30.itemSpacing = 0;
c30.paddingTop = 8;
c30.paddingRight = 12;
c30.paddingBottom = 8;
c30.paddingLeft = 12;
c30.primaryAxisSizingMode = 'AUTO';
c30.counterAxisSizingMode = 'AUTO';
c30.fills = [];
var c31 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Medium' });
c31.fontName = { family: 'Inter', style: 'Medium' };
c31.fontSize = 14;
c31.characters = 'Focused';
c31.fills = [{ type: 'SOLID', color: hexToRgb('#1A1A2E') }];
c31.resize(140, c31.height);
c31.textAutoResize = 'HEIGHT';
c30.appendChild(c31);
var c32 = figma.createFrame();
c32.name = 'Cell: theme-primary';
c32.layoutMode = 'HORIZONTAL';
c32.itemSpacing = 6;
c32.paddingTop = 0;
c32.paddingRight = 0;
c32.paddingBottom = 0;
c32.paddingLeft = 0;
c32.primaryAxisSizingMode = 'AUTO';
c32.counterAxisSizingMode = 'AUTO';
c32.fills = [];
var c33 = figma.createEllipse();
c33.name = 'Swatch';
c33.resize(16, 16);
c33.fills = [{ type: 'SOLID', color: hexToRgb('#0550DC') }];
c32.appendChild(c33);
var c34 = figma.createText();
await figma.loadFontAsync({ family: 'Fira Code', style: 'Regular' });
c34.fontName = { family: 'Fira Code', style: 'Regular' };
c34.fontSize = 11;
c34.characters = 'theme-primary #0550DC';
c34.fills = [{ type: 'SOLID', color: hexToRgb('#595968') }];
c32.appendChild(c34);
c30.appendChild(c32);
c32.layoutSizingHorizontal = 'HUG';
c32.layoutSizingVertical = 'HUG';
var c35 = figma.createFrame();
c35.name = 'Cell: theme-primary';
c35.layoutMode = 'HORIZONTAL';
c35.itemSpacing = 6;
c35.paddingTop = 0;
c35.paddingRight = 0;
c35.paddingBottom = 0;
c35.paddingLeft = 0;
c35.primaryAxisSizingMode = 'AUTO';
c35.counterAxisSizingMode = 'AUTO';
c35.fills = [];
var c36 = figma.createEllipse();
c36.name = 'Swatch';
c36.resize(16, 16);
c36.fills = [{ type: 'SOLID', color: hexToRgb('#0550DC') }];
c35.appendChild(c36);
var c37 = figma.createText();
await figma.loadFontAsync({ family: 'Fira Code', style: 'Regular' });
c37.fontName = { family: 'Fira Code', style: 'Regular' };
c37.fontSize = 11;
c37.characters = 'theme-primary #0550DC';
c37.fills = [{ type: 'SOLID', color: hexToRgb('#595968') }];
c35.appendChild(c37);
c30.appendChild(c35);
c35.layoutSizingHorizontal = 'HUG';
c35.layoutSizingVertical = 'HUG';
var c38 = figma.createFrame();
c38.name = 'Cell: theme-primary';
c38.layoutMode = 'HORIZONTAL';
c38.itemSpacing = 6;
c38.paddingTop = 0;
c38.paddingRight = 0;
c38.paddingBottom = 0;
c38.paddingLeft = 0;
c38.primaryAxisSizingMode = 'AUTO';
c38.counterAxisSizingMode = 'AUTO';
c38.fills = [];
var c39 = figma.createEllipse();
c39.name = 'Swatch';
c39.resize(16, 16);
c39.fills = [{ type: 'SOLID', color: hexToRgb('#0550DC') }];
c38.appendChild(c39);
var c40 = figma.createText();
await figma.loadFontAsync({ family: 'Fira Code', style: 'Regular' });
c40.fontName = { family: 'Fira Code', style: 'Regular' };
c40.fontSize = 11;
c40.characters = 'theme-primary #0550DC';
c40.fills = [{ type: 'SOLID', color: hexToRgb('#595968') }];
c38.appendChild(c40);
c30.appendChild(c38);
c38.layoutSizingHorizontal = 'HUG';
c38.layoutSizingVertical = 'HUG';
c2.appendChild(c30);
_fillH(c30);
c30.layoutSizingVertical = 'HUG';
var c41 = figma.createFrame();
c41.name = 'Row 3';
c41.layoutMode = 'HORIZONTAL';
c41.itemSpacing = 0;
c41.paddingTop = 8;
c41.paddingRight = 12;
c41.paddingBottom = 8;
c41.paddingLeft = 12;
c41.primaryAxisSizingMode = 'AUTO';
c41.counterAxisSizingMode = 'AUTO';
c41.fills = [];
var c42 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Medium' });
c42.fontName = { family: 'Inter', style: 'Medium' };
c42.fontSize = 14;
c42.characters = 'Pressed';
c42.fills = [{ type: 'SOLID', color: hexToRgb('#1A1A2E') }];
c42.resize(140, c42.height);
c42.textAutoResize = 'HEIGHT';
c41.appendChild(c42);
var c43 = figma.createFrame();
c43.name = 'Cell: theme-primary-pressed';
c43.layoutMode = 'HORIZONTAL';
c43.itemSpacing = 6;
c43.paddingTop = 0;
c43.paddingRight = 0;
c43.paddingBottom = 0;
c43.paddingLeft = 0;
c43.primaryAxisSizingMode = 'AUTO';
c43.counterAxisSizingMode = 'AUTO';
c43.fills = [];
var c44 = figma.createEllipse();
c44.name = 'Swatch';
c44.resize(16, 16);
c44.fills = [{ type: 'SOLID', color: hexToRgb('#023699') }];
c43.appendChild(c44);
var c45 = figma.createText();
await figma.loadFontAsync({ family: 'Fira Code', style: 'Regular' });
c45.fontName = { family: 'Fira Code', style: 'Regular' };
c45.fontSize = 11;
c45.characters = 'theme-primary-pressed #023699';
c45.fills = [{ type: 'SOLID', color: hexToRgb('#595968') }];
c43.appendChild(c45);
c41.appendChild(c43);
c43.layoutSizingHorizontal = 'HUG';
c43.layoutSizingVertical = 'HUG';
var c46 = figma.createFrame();
c46.name = 'Cell: theme-primary-pressed';
c46.layoutMode = 'HORIZONTAL';
c46.itemSpacing = 6;
c46.paddingTop = 0;
c46.paddingRight = 0;
c46.paddingBottom = 0;
c46.paddingLeft = 0;
c46.primaryAxisSizingMode = 'AUTO';
c46.counterAxisSizingMode = 'AUTO';
c46.fills = [];
var c47 = figma.createEllipse();
c47.name = 'Swatch';
c47.resize(16, 16);
c47.fills = [{ type: 'SOLID', color: hexToRgb('#023699') }];
c46.appendChild(c47);
var c48 = figma.createText();
await figma.loadFontAsync({ family: 'Fira Code', style: 'Regular' });
c48.fontName = { family: 'Fira Code', style: 'Regular' };
c48.fontSize = 11;
c48.characters = 'theme-primary-pressed #023699';
c48.fills = [{ type: 'SOLID', color: hexToRgb('#595968') }];
c46.appendChild(c48);
c41.appendChild(c46);
c46.layoutSizingHorizontal = 'HUG';
c46.layoutSizingVertical = 'HUG';
var c49 = figma.createFrame();
c49.name = 'Cell: theme-primary-pressed';
c49.layoutMode = 'HORIZONTAL';
c49.itemSpacing = 6;
c49.paddingTop = 0;
c49.paddingRight = 0;
c49.paddingBottom = 0;
c49.paddingLeft = 0;
c49.primaryAxisSizingMode = 'AUTO';
c49.counterAxisSizingMode = 'AUTO';
c49.fills = [];
var c50 = figma.createEllipse();
c50.name = 'Swatch';
c50.resize(16, 16);
c50.fills = [{ type: 'SOLID', color: hexToRgb('#023699') }];
c49.appendChild(c50);
var c51 = figma.createText();
await figma.loadFontAsync({ family: 'Fira Code', style: 'Regular' });
c51.fontName = { family: 'Fira Code', style: 'Regular' };
c51.fontSize = 11;
c51.characters = 'theme-primary-pressed #023699';
c51.fills = [{ type: 'SOLID', color: hexToRgb('#595968') }];
c49.appendChild(c51);
c41.appendChild(c49);
c49.layoutSizingHorizontal = 'HUG';
c49.layoutSizingVertical = 'HUG';
c2.appendChild(c41);
_fillH(c41);
c41.layoutSizingVertical = 'HUG';
var c52 = figma.createFrame();
c52.name = 'Row 4';
c52.layoutMode = 'HORIZONTAL';
c52.itemSpacing = 0;
c52.paddingTop = 8;
c52.paddingRight = 12;
c52.paddingBottom = 8;
c52.paddingLeft = 12;
c52.primaryAxisSizingMode = 'AUTO';
c52.counterAxisSizingMode = 'AUTO';
c52.fills = [];
var c53 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Medium' });
c53.fontName = { family: 'Inter', style: 'Medium' };
c53.fontSize = 14;
c53.characters = 'Disabled';
c53.fills = [{ type: 'SOLID', color: hexToRgb('#1A1A2E') }];
c53.resize(140, c53.height);
c53.textAutoResize = 'HEIGHT';
c52.appendChild(c53);
var c54 = figma.createFrame();
c54.name = 'Cell: text-disabled';
c54.layoutMode = 'HORIZONTAL';
c54.itemSpacing = 6;
c54.paddingTop = 0;
c54.paddingRight = 0;
c54.paddingBottom = 0;
c54.paddingLeft = 0;
c54.primaryAxisSizingMode = 'AUTO';
c54.counterAxisSizingMode = 'AUTO';
c54.fills = [];
var c55 = figma.createEllipse();
c55.name = 'Swatch';
c55.resize(16, 16);
c55.fills = [{ type: 'SOLID', color: hexToRgb('#9898A7') }];
c54.appendChild(c55);
var c56 = figma.createText();
await figma.loadFontAsync({ family: 'Fira Code', style: 'Regular' });
c56.fontName = { family: 'Fira Code', style: 'Regular' };
c56.fontSize = 11;
c56.characters = 'text-disabled #9898A7';
c56.fills = [{ type: 'SOLID', color: hexToRgb('#595968') }];
c54.appendChild(c56);
c52.appendChild(c54);
c54.layoutSizingHorizontal = 'HUG';
c54.layoutSizingVertical = 'HUG';
var c57 = figma.createFrame();
c57.name = 'Cell: text-disabled';
c57.layoutMode = 'HORIZONTAL';
c57.itemSpacing = 6;
c57.paddingTop = 0;
c57.paddingRight = 0;
c57.paddingBottom = 0;
c57.paddingLeft = 0;
c57.primaryAxisSizingMode = 'AUTO';
c57.counterAxisSizingMode = 'AUTO';
c57.fills = [];
var c58 = figma.createEllipse();
c58.name = 'Swatch';
c58.resize(16, 16);
c58.fills = [{ type: 'SOLID', color: hexToRgb('#9898A7') }];
c57.appendChild(c58);
var c59 = figma.createText();
await figma.loadFontAsync({ family: 'Fira Code', style: 'Regular' });
c59.fontName = { family: 'Fira Code', style: 'Regular' };
c59.fontSize = 11;
c59.characters = 'text-disabled #9898A7';
c59.fills = [{ type: 'SOLID', color: hexToRgb('#595968') }];
c57.appendChild(c59);
c52.appendChild(c57);
c57.layoutSizingHorizontal = 'HUG';
c57.layoutSizingVertical = 'HUG';
var c60 = figma.createFrame();
c60.name = 'Cell: —';
c60.layoutMode = 'HORIZONTAL';
c60.itemSpacing = 6;
c60.paddingTop = 0;
c60.paddingRight = 0;
c60.paddingBottom = 0;
c60.paddingLeft = 0;
c60.primaryAxisSizingMode = 'AUTO';
c60.counterAxisSizingMode = 'AUTO';
c60.fills = [];
var c61 = figma.createEllipse();
c61.name = 'Swatch';
c61.resize(16, 16);
c61.fills = [];
c60.appendChild(c61);
var c62 = figma.createText();
await figma.loadFontAsync({ family: 'Fira Code', style: 'Regular' });
c62.fontName = { family: 'Fira Code', style: 'Regular' };
c62.fontSize = 11;
c62.characters = '— transparent';
c62.fills = [{ type: 'SOLID', color: hexToRgb('#595968') }];
c60.appendChild(c62);
c52.appendChild(c60);
c60.layoutSizingHorizontal = 'HUG';
c60.layoutSizingVertical = 'HUG';
c2.appendChild(c52);
_fillH(c52);
c52.layoutSizingVertical = 'HUG';
c0_slot.appendChild(c2);
_fillH(c2);
c2.layoutSizingVertical = 'HUG';
var c63 = figma.createRectangle();
c63.name = 'Divider';
c63.resize(300, 1);
c63.fills = [{ type: 'SOLID', color: hexToRgb('#E0E0E0') }];
c0_slot.appendChild(c63);
var c64 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Semi Bold' });
c64.fontName = { family: 'Inter', style: 'Semi Bold' };
c64.fontSize = 16;
c64.characters = 'Sizing & spacing';
c64.fills = [{ type: 'SOLID', color: hexToRgb('#1A1A2E') }];
c0_slot.appendChild(c64);
var c65 = figma.createFrame();
c65.name = 'Sizing table';
c65.layoutMode = 'VERTICAL';
c65.itemSpacing = 0;
c65.paddingTop = 0;
c65.paddingRight = 0;
c65.paddingBottom = 0;
c65.paddingLeft = 0;
c65.primaryAxisSizingMode = 'AUTO';
c65.counterAxisSizingMode = 'AUTO';
c65.fills = [];
var c66 = figma.createFrame();
c66.name = 'Header';
c66.layoutMode = 'HORIZONTAL';
c66.itemSpacing = 0;
c66.paddingTop = 8;
c66.paddingRight = 12;
c66.paddingBottom = 8;
c66.paddingLeft = 12;
c66.primaryAxisSizingMode = 'AUTO';
c66.counterAxisSizingMode = 'AUTO';
c66.fills = [{ type: 'SOLID', color: hexToRgb('#F5F5FA') }];
var c67 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Bold' });
c67.fontName = { family: 'Inter', style: 'Bold' };
c67.fontSize = 12;
c67.characters = 'Property';
c67.fills = [{ type: 'SOLID', color: hexToRgb('#595968') }];
c67.resize(200, c67.height);
c67.textAutoResize = 'HEIGHT';
c66.appendChild(c67);
var c68 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Bold' });
c68.fontName = { family: 'Inter', style: 'Bold' };
c68.fontSize = 12;
c68.characters = 'Token';
c68.fills = [{ type: 'SOLID', color: hexToRgb('#595968') }];
c68.resize(240, c68.height);
c68.textAutoResize = 'HEIGHT';
c66.appendChild(c68);
var c69 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Bold' });
c69.fontName = { family: 'Inter', style: 'Bold' };
c69.fontSize = 12;
c69.characters = 'Value';
c69.fills = [{ type: 'SOLID', color: hexToRgb('#595968') }];
c69.resize(120, c69.height);
c69.textAutoResize = 'HEIGHT';
c66.appendChild(c69);
c65.appendChild(c66);
_fillH(c66);
c66.layoutSizingVertical = 'HUG';
var c70 = figma.createFrame();
c70.name = 'Row 0';
c70.layoutMode = 'HORIZONTAL';
c70.itemSpacing = 0;
c70.paddingTop = 8;
c70.paddingRight = 12;
c70.paddingBottom = 8;
c70.paddingLeft = 12;
c70.primaryAxisSizingMode = 'AUTO';
c70.counterAxisSizingMode = 'AUTO';
c70.fills = [];
var c71 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });
c71.fontName = { family: 'Inter', style: 'Regular' };
c71.fontSize = 14;
c71.characters = 'Icon size';
c71.fills = [{ type: 'SOLID', color: hexToRgb('#1A1A2E') }];
c71.resize(200, c71.height);
c71.textAutoResize = 'HEIGHT';
c70.appendChild(c71);
var c72 = figma.createText();
await figma.loadFontAsync({ family: 'Fira Code', style: 'Regular' });
c72.fontName = { family: 'Fira Code', style: 'Regular' };
c72.fontSize = 12;
c72.characters = '--zen-size-md';
c72.fills = [{ type: 'SOLID', color: hexToRgb('#1A1A2E') }];
c72.resize(240, c72.height);
c72.textAutoResize = 'HEIGHT';
c70.appendChild(c72);
var c73 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });
c73.fontName = { family: 'Inter', style: 'Regular' };
c73.fontSize = 14;
c73.characters = '16px';
c73.fills = [{ type: 'SOLID', color: hexToRgb('#1A1A2E') }];
c73.resize(120, c73.height);
c73.textAutoResize = 'HEIGHT';
c70.appendChild(c73);
c65.appendChild(c70);
_fillH(c70);
c70.layoutSizingVertical = 'HUG';
var c74 = figma.createFrame();
c74.name = 'Row 1';
c74.layoutMode = 'HORIZONTAL';
c74.itemSpacing = 0;
c74.paddingTop = 8;
c74.paddingRight = 12;
c74.paddingBottom = 8;
c74.paddingLeft = 12;
c74.primaryAxisSizingMode = 'AUTO';
c74.counterAxisSizingMode = 'AUTO';
c74.fills = [];
var c75 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });
c75.fontName = { family: 'Inter', style: 'Regular' };
c75.fontSize = 14;
c75.characters = 'Text-to-icon gap';
c75.fills = [{ type: 'SOLID', color: hexToRgb('#1A1A2E') }];
c75.resize(200, c75.height);
c75.textAutoResize = 'HEIGHT';
c74.appendChild(c75);
var c76 = figma.createText();
await figma.loadFontAsync({ family: 'Fira Code', style: 'Regular' });
c76.fontName = { family: 'Fira Code', style: 'Regular' };
c76.fontSize = 12;
c76.characters = '--zen-spacing-2xs';
c76.fills = [{ type: 'SOLID', color: hexToRgb('#1A1A2E') }];
c76.resize(240, c76.height);
c76.textAutoResize = 'HEIGHT';
c74.appendChild(c76);
var c77 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });
c77.fontName = { family: 'Inter', style: 'Regular' };
c77.fontSize = 14;
c77.characters = '4px';
c77.fills = [{ type: 'SOLID', color: hexToRgb('#1A1A2E') }];
c77.resize(120, c77.height);
c77.textAutoResize = 'HEIGHT';
c74.appendChild(c77);
c65.appendChild(c74);
_fillH(c74);
c74.layoutSizingVertical = 'HUG';
var c78 = figma.createFrame();
c78.name = 'Row 2';
c78.layoutMode = 'HORIZONTAL';
c78.itemSpacing = 0;
c78.paddingTop = 8;
c78.paddingRight = 12;
c78.paddingBottom = 8;
c78.paddingLeft = 12;
c78.primaryAxisSizingMode = 'AUTO';
c78.counterAxisSizingMode = 'AUTO';
c78.fills = [];
var c79 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });
c79.fontName = { family: 'Inter', style: 'Regular' };
c79.fontSize = 14;
c79.characters = 'Focus ring offset';
c79.fills = [{ type: 'SOLID', color: hexToRgb('#1A1A2E') }];
c79.resize(200, c79.height);
c79.textAutoResize = 'HEIGHT';
c78.appendChild(c79);
var c80 = figma.createText();
await figma.loadFontAsync({ family: 'Fira Code', style: 'Regular' });
c80.fontName = { family: 'Fira Code', style: 'Regular' };
c80.fontSize = 12;
c80.characters = '--zen-spacing-3xs';
c80.fills = [{ type: 'SOLID', color: hexToRgb('#1A1A2E') }];
c80.resize(240, c80.height);
c80.textAutoResize = 'HEIGHT';
c78.appendChild(c80);
var c81 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });
c81.fontName = { family: 'Inter', style: 'Regular' };
c81.fontSize = 14;
c81.characters = '2px';
c81.fills = [{ type: 'SOLID', color: hexToRgb('#1A1A2E') }];
c81.resize(120, c81.height);
c81.textAutoResize = 'HEIGHT';
c78.appendChild(c81);
c65.appendChild(c78);
_fillH(c78);
c78.layoutSizingVertical = 'HUG';
var c82 = figma.createFrame();
c82.name = 'Row 3';
c82.layoutMode = 'HORIZONTAL';
c82.itemSpacing = 0;
c82.paddingTop = 8;
c82.paddingRight = 12;
c82.paddingBottom = 8;
c82.paddingLeft = 12;
c82.primaryAxisSizingMode = 'AUTO';
c82.counterAxisSizingMode = 'AUTO';
c82.fills = [];
var c83 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });
c83.fontName = { family: 'Inter', style: 'Regular' };
c83.fontSize = 14;
c83.characters = 'Focus ring width';
c83.fills = [{ type: 'SOLID', color: hexToRgb('#1A1A2E') }];
c83.resize(200, c83.height);
c83.textAutoResize = 'HEIGHT';
c82.appendChild(c83);
var c84 = figma.createText();
await figma.loadFontAsync({ family: 'Fira Code', style: 'Regular' });
c84.fontName = { family: 'Fira Code', style: 'Regular' };
c84.fontSize = 12;
c84.characters = '—';
c84.fills = [{ type: 'SOLID', color: hexToRgb('#1A1A2E') }];
c84.resize(240, c84.height);
c84.textAutoResize = 'HEIGHT';
c82.appendChild(c84);
var c85 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });
c85.fontName = { family: 'Inter', style: 'Regular' };
c85.fontSize = 14;
c85.characters = '2px';
c85.fills = [{ type: 'SOLID', color: hexToRgb('#1A1A2E') }];
c85.resize(120, c85.height);
c85.textAutoResize = 'HEIGHT';
c82.appendChild(c85);
c65.appendChild(c82);
_fillH(c82);
c82.layoutSizingVertical = 'HUG';
c0_slot.appendChild(c65);
_fillH(c65);
c65.layoutSizingVertical = 'HUG';
var c86 = figma.createRectangle();
c86.name = 'Divider';
c86.resize(300, 1);
c86.fills = [{ type: 'SOLID', color: hexToRgb('#E0E0E0') }];
c0_slot.appendChild(c86);
var c87 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Semi Bold' });
c87.fontName = { family: 'Inter', style: 'Semi Bold' };
c87.fontSize = 16;
c87.characters = 'Typography';
c87.fills = [{ type: 'SOLID', color: hexToRgb('#1A1A2E') }];
c0_slot.appendChild(c87);
var c88 = figma.createFrame();
c88.name = 'Typography: Link text';
c88.layoutMode = 'VERTICAL';
c88.itemSpacing = 4;
c88.paddingTop = 8;
c88.paddingRight = 0;
c88.paddingBottom = 8;
c88.paddingLeft = 0;
c88.primaryAxisSizingMode = 'AUTO';
c88.counterAxisSizingMode = 'AUTO';
c88.fills = [];
var c89 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Semi Bold' });
c89.fontName = { family: 'Inter', style: 'Semi Bold' };
c89.fontSize = 14;
c89.characters = 'Link text';
c89.fills = [{ type: 'SOLID', color: hexToRgb('#1A1A2E') }];
c88.appendChild(c89);
var c90 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });
c90.fontName = { family: 'Inter', style: 'Regular' };
c90.fontSize = 12;
c90.characters = 'body-standard — Roboto Regular 14px/20px, tracking 0.2px';
c90.fills = [{ type: 'SOLID', color: hexToRgb('#595968') }];
c88.appendChild(c90);
c0_slot.appendChild(c88);
_fillH(c88);
c88.layoutSizingVertical = 'HUG';
_wrapper.appendChild(c0);
_nodeCount++;

// Tag with plugin data
_wrapper.setSharedPluginData('actian_ds', 'skill', 'component-brief');
_wrapper.setSharedPluginData('actian_ds', 'pushed_at', new Date().toISOString());

// Return metadata
return { wrapperId: _wrapper.id, nodeCount: _nodeCount };