function hexToRgb(hex) {
  var h = hex.replace('#', '');
  return {
    r: parseInt(h.substring(0, 2), 16) / 255,
    g: parseInt(h.substring(2, 4), 16) / 255,
    b: parseInt(h.substring(4, 6), 16) / 255
  };
}

function angleToTransform(angleDeg) {
  var rad = (angleDeg * Math.PI) / 180;
  var cos = Math.cos(rad);
  var sin = Math.sin(rad);
  return [
    [cos, sin, 0.5 - 0.5 * cos - 0.5 * sin],
    [-sin, cos, 0.5 + 0.5 * sin - 0.5 * cos]
  ];
}

function setProp(instance, prefix, value) {
  var props = instance.componentProperties;
  for (var key in props) {
    var propName = key.split('#')[0];
    if (propName === prefix) {
      instance.setProperties({ [key]: value });
      return;
    }
  }
}

function _fillH(n) {
  var p = n.parent; if (!p) return;
  if (p.layoutMode && p.layoutMode !== 'NONE') { n.layoutSizingHorizontal = 'FILL'; }
  else { n.resize(Math.max((p.width||0)-(p.paddingLeft||0)-(p.paddingRight||0),1), n.height); }
}
function _fillV(n) {
  var p = n.parent; if (!p) return;
  if (p.layoutMode && p.layoutMode !== 'NONE') { n.layoutSizingVertical = 'FILL'; }
  else { n.resize(n.width, Math.max((p.height||0)-(p.paddingTop||0)-(p.paddingBottom||0),1)); }
}


// Navigate to target page
var _targetNode = await figma.getNodeByIdAsync(undefined);
var _page = _targetNode;
while (_page && _page.type !== 'PAGE') _page = _page.parent;
if (_page) await figma.setCurrentPageAsync(_page);

// Load fonts
await Promise.all([
  figma.loadFontAsync({ family: 'Inter', style: 'Regular' }),
  figma.loadFontAsync({ family: 'Inter', style: 'Semi Bold' }),
  figma.loadFontAsync({ family: 'Inter', style: 'Bold' }),
  figma.loadFontAsync({ family: 'Inter', style: 'Medium' }),
  figma.loadFontAsync({ family: 'Fira Code', style: 'Regular' }),
  figma.loadFontAsync({ family: 'Roboto', style: 'Regular' }),
]);

// Import components
var _imp_genLog = await figma.importComponentByKeyAsync('a9653f30925367e96dea90093d750bfe70849571');
var _imp_divider = await figma.importComponentByKeyAsync('f4d778e1cf9bb61a33712c791486f54bb1c095b7');
var _imp_codeBlock = await figma.importComponentByKeyAsync('1bf10eee1751a46da5f90a9671be6c9abf0073b7');
var _imp_flowCoverCard = await figma.importComponentByKeyAsync('eaebde6bd07d2f19f3f9c00a9587240cb085a90d');
var _imp_researchFrame = await figma.importComponentByKeyAsync('e671618f2b4c6ea406a995fdc3012ac54eadfe56');
var _imp_feedback = await figma.importComponentSetByKeyAsync('d5cba21bc3dbf36578665bac89834fbe1ca29ed0');
var _imp_briefCard = await figma.importComponentSetByKeyAsync('3dbb732730af0754210cde7af35e5236a2502843');
var _imp_doDontPair = await figma.importComponentSetByKeyAsync('28edfacf13e50706586172bd48f8a3ad84d7c263');
var _imp_contrastBadge = await figma.importComponentSetByKeyAsync('941756541adc6ce21e32e848c2039c64fece0fcf');
var _imp_pointerBadge = await figma.importComponentSetByKeyAsync('7e066fc21d9a2bbbcd1149113787cf59140162d4');
var _imp_dimAnnotation = await figma.importComponentSetByKeyAsync('49bf6a1b210a403ba145a3fdee9b1994eb54069a');
var _imp_a11yCard = await figma.importComponentSetByKeyAsync('b4779a13f4097d682413a669eaaf9ead1b49f115');

// Load local components
var _local_targetComponent = await figma.importComponentSetByKeyAsync('675f7f8d0d57162e4cce51d26cbe39cf490e9b8d');

// Create or find wrapper
var _wrapper = await figma.getNodeByIdAsync('__WRAPPER_ID__');
if (!_wrapper) throw new Error('Wrapper __WRAPPER_ID__ not found');

// Build tree
var _nodeCount = 0;
var c0;
(function() {
  var _cs = _imp_briefCard;
  if (_cs.type === 'COMPONENT_SET') {
    var _variants = _cs.children;
    var _target = null;
    for (var _i = 0; _i < _variants.length; _i++) {
      if (_variants[_i].name === 'Mode=DS, Type=Standard') { _target = _variants[_i]; break; }
    }
    if (!_target) {
      for (var _j = 0; _j < _variants.length; _j++) {
        if (_variants[_j].name.indexOf('Mode=DS, Type=Standard') !== -1) { _target = _variants[_j]; break; }
      }
    }
    if (_target) {
      c0 = _target.createInstance();
    } else {
      c0 = (_cs.defaultVariant || _cs.children[0]).createInstance();
    }
  } else {
    c0 = _cs.createInstance();
  }
})();
c0.name = 'Component API';
c0.resize(1200, c0.height);
setProp(c0, 'Title', 'Component API');
setProp(c0, 'Subtitle', 'Properties, types, defaults, and allowed values');
c0 = c0.detachInstance();
var c0_slot = c0.findOne(function(n) { return n.name === "Content"; }) || c0;
if (c0_slot !== c0) {
  while (c0_slot.children.length) c0_slot.children[0].remove();
}
if (c0_slot !== c0) {
  c0_slot.layoutMode = 'VERTICAL';
  c0_slot.itemSpacing = 16;
  c0_slot.paddingTop = 48;
  c0_slot.paddingRight = 80;
  c0_slot.paddingBottom = 48;
  c0_slot.paddingLeft = 80;
  c0_slot.primaryAxisSizingMode = 'AUTO';
  c0_slot.counterAxisSizingMode = 'AUTO';
  c0.primaryAxisSizingMode = 'AUTO';
}
var c1 = figma.createFrame();
c1.name = 'API table';
c1.layoutMode = 'VERTICAL';
c1.itemSpacing = 0;
c1.paddingTop = 0;
c1.paddingRight = 0;
c1.paddingBottom = 0;
c1.paddingLeft = 0;
c1.primaryAxisSizingMode = 'AUTO';
c1.counterAxisSizingMode = 'AUTO';
c1.fills = [];
var c2 = figma.createFrame();
c2.name = 'Header';
c2.layoutMode = 'HORIZONTAL';
c2.itemSpacing = 0;
c2.paddingTop = 8;
c2.paddingRight = 12;
c2.paddingBottom = 8;
c2.paddingLeft = 12;
c2.primaryAxisSizingMode = 'AUTO';
c2.counterAxisSizingMode = 'AUTO';
c2.fills = [{ type: 'SOLID', color: hexToRgb('#F5F5FA') }];
var c3 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Bold' });
c3.fontName = { family: 'Inter', style: 'Bold' };
c3.fontSize = 12;
c3.characters = '';
c3.fills = [{ type: 'SOLID', color: hexToRgb('#595968') }];
c3.resize(50, c3.height);
c3.textAutoResize = 'HEIGHT';
c2.appendChild(c3);
var c4 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Bold' });
c4.fontName = { family: 'Inter', style: 'Bold' };
c4.fontSize = 12;
c4.characters = 'Property';
c4.fills = [{ type: 'SOLID', color: hexToRgb('#595968') }];
c4.resize(140, c4.height);
c4.textAutoResize = 'HEIGHT';
c2.appendChild(c4);
var c5 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Bold' });
c5.fontName = { family: 'Inter', style: 'Bold' };
c5.fontSize = 12;
c5.characters = 'Type';
c5.fills = [{ type: 'SOLID', color: hexToRgb('#595968') }];
c5.resize(100, c5.height);
c5.textAutoResize = 'HEIGHT';
c2.appendChild(c5);
var c6 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Bold' });
c6.fontName = { family: 'Inter', style: 'Bold' };
c6.fontSize = 12;
c6.characters = 'Default';
c6.fills = [{ type: 'SOLID', color: hexToRgb('#595968') }];
c6.resize(120, c6.height);
c6.textAutoResize = 'HEIGHT';
c2.appendChild(c6);
var c7 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Bold' });
c7.fontName = { family: 'Inter', style: 'Bold' };
c7.fontSize = 12;
c7.characters = 'Values';
c7.fills = [{ type: 'SOLID', color: hexToRgb('#595968') }];
c7.resize(200, c7.height);
c7.textAutoResize = 'HEIGHT';
c2.appendChild(c7);
var c8 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Bold' });
c8.fontName = { family: 'Inter', style: 'Bold' };
c8.fontSize = 12;
c8.characters = 'Notes';
c8.fills = [{ type: 'SOLID', color: hexToRgb('#595968') }];
c8.resize(350, c8.height);
c8.textAutoResize = 'HEIGHT';
c2.appendChild(c8);
c1.appendChild(c2);
_fillH(c2);
c2.layoutSizingVertical = 'HUG';
var c9 = figma.createFrame();
c9.name = 'Row 0';
c9.layoutMode = 'HORIZONTAL';
c9.itemSpacing = 0;
c9.paddingTop = 8;
c9.paddingRight = 12;
c9.paddingBottom = 8;
c9.paddingLeft = 12;
c9.primaryAxisSizingMode = 'AUTO';
c9.counterAxisSizingMode = 'AUTO';
c9.fills = [];
var c10 = figma.createFrame();
c10.name = 'REQ badge';
c10.layoutMode = 'HORIZONTAL';
c10.paddingTop = 2;
c10.paddingRight = 6;
c10.paddingBottom = 2;
c10.paddingLeft = 6;
c10.primaryAxisSizingMode = 'AUTO';
c10.counterAxisSizingMode = 'AUTO';
c10.fills = [{ type: 'SOLID', color: hexToRgb('#FEF3F2') }];
c10.cornerRadius = 4;
var c11 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Bold' });
c11.fontName = { family: 'Inter', style: 'Bold' };
c11.fontSize = 10;
c11.characters = 'REQ';
c11.fills = [{ type: 'SOLID', color: hexToRgb('#C10C0D') }];
c10.appendChild(c11);
c9.appendChild(c10);
var c12 = figma.createText();
await figma.loadFontAsync({ family: 'Fira Code', style: 'Regular' });
c12.fontName = { family: 'Fira Code', style: 'Regular' };
c12.fontSize = 12;
c12.characters = 'href';
c12.fills = [{ type: 'SOLID', color: hexToRgb('#1A1A2E') }];
c12.resize(140, c12.height);
c12.textAutoResize = 'HEIGHT';
c9.appendChild(c12);
var c13 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });
c13.fontName = { family: 'Inter', style: 'Regular' };
c13.fontSize = 14;
c13.characters = 'string';
c13.fills = [{ type: 'SOLID', color: hexToRgb('#C792EA') }];
c13.resize(100, c13.height);
c13.textAutoResize = 'HEIGHT';
c9.appendChild(c13);
var c14 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });
c14.fontName = { family: 'Inter', style: 'Regular' };
c14.fontSize = 14;
c14.characters = '—';
c14.fills = [{ type: 'SOLID', color: hexToRgb('#C3E88D') }];
c14.resize(120, c14.height);
c14.textAutoResize = 'HEIGHT';
c9.appendChild(c14);
var c15 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });
c15.fontName = { family: 'Inter', style: 'Regular' };
c15.fontSize = 14;
c15.characters = 'any URL';
c15.fills = [{ type: 'SOLID', color: hexToRgb('#1A1A2E') }];
c15.resize(200, c15.height);
c15.textAutoResize = 'HEIGHT';
c9.appendChild(c15);
var c16 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });
c16.fontName = { family: 'Inter', style: 'Regular' };
c16.fontSize = 14;
c16.characters = 'Navigation destination';
c16.fills = [{ type: 'SOLID', color: hexToRgb('#595968') }];
c16.resize(350, c16.height);
c16.textAutoResize = 'HEIGHT';
c9.appendChild(c16);
c1.appendChild(c9);
_fillH(c9);
c9.layoutSizingVertical = 'HUG';
var c17 = figma.createFrame();
c17.name = 'Row 1';
c17.layoutMode = 'HORIZONTAL';
c17.itemSpacing = 0;
c17.paddingTop = 8;
c17.paddingRight = 12;
c17.paddingBottom = 8;
c17.paddingLeft = 12;
c17.primaryAxisSizingMode = 'AUTO';
c17.counterAxisSizingMode = 'AUTO';
c17.fills = [];
var c18 = figma.createFrame();
c18.name = 'REQ badge';
c18.layoutMode = 'HORIZONTAL';
c18.paddingTop = 2;
c18.paddingRight = 6;
c18.paddingBottom = 2;
c18.paddingLeft = 6;
c18.primaryAxisSizingMode = 'AUTO';
c18.counterAxisSizingMode = 'AUTO';
c18.fills = [{ type: 'SOLID', color: hexToRgb('#FEF3F2') }];
c18.cornerRadius = 4;
var c19 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Bold' });
c19.fontName = { family: 'Inter', style: 'Bold' };
c19.fontSize = 10;
c19.characters = 'REQ';
c19.fills = [{ type: 'SOLID', color: hexToRgb('#C10C0D') }];
c18.appendChild(c19);
c17.appendChild(c18);
var c20 = figma.createText();
await figma.loadFontAsync({ family: 'Fira Code', style: 'Regular' });
c20.fontName = { family: 'Fira Code', style: 'Regular' };
c20.fontSize = 12;
c20.characters = 'children';
c20.fills = [{ type: 'SOLID', color: hexToRgb('#1A1A2E') }];
c20.resize(140, c20.height);
c20.textAutoResize = 'HEIGHT';
c17.appendChild(c20);
var c21 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });
c21.fontName = { family: 'Inter', style: 'Regular' };
c21.fontSize = 14;
c21.characters = 'ReactNode';
c21.fills = [{ type: 'SOLID', color: hexToRgb('#C792EA') }];
c21.resize(100, c21.height);
c21.textAutoResize = 'HEIGHT';
c17.appendChild(c21);
var c22 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });
c22.fontName = { family: 'Inter', style: 'Regular' };
c22.fontSize = 14;
c22.characters = '—';
c22.fills = [{ type: 'SOLID', color: hexToRgb('#C3E88D') }];
c22.resize(120, c22.height);
c22.textAutoResize = 'HEIGHT';
c17.appendChild(c22);
var c23 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });
c23.fontName = { family: 'Inter', style: 'Regular' };
c23.fontSize = 14;
c23.characters = 'text content';
c23.fills = [{ type: 'SOLID', color: hexToRgb('#1A1A2E') }];
c23.resize(200, c23.height);
c23.textAutoResize = 'HEIGHT';
c17.appendChild(c23);
var c24 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });
c24.fontName = { family: 'Inter', style: 'Regular' };
c24.fontSize = 14;
c24.characters = 'Visible link label';
c24.fills = [{ type: 'SOLID', color: hexToRgb('#595968') }];
c24.resize(350, c24.height);
c24.textAutoResize = 'HEIGHT';
c17.appendChild(c24);
c1.appendChild(c17);
_fillH(c17);
c17.layoutSizingVertical = 'HUG';
var c25 = figma.createFrame();
c25.name = 'Row 2';
c25.layoutMode = 'HORIZONTAL';
c25.itemSpacing = 0;
c25.paddingTop = 8;
c25.paddingRight = 12;
c25.paddingBottom = 8;
c25.paddingLeft = 12;
c25.primaryAxisSizingMode = 'AUTO';
c25.counterAxisSizingMode = 'AUTO';
c25.fills = [];
var c26 = figma.createFrame();
c26.name = 'OPT badge';
c26.layoutMode = 'HORIZONTAL';
c26.paddingTop = 2;
c26.paddingRight = 6;
c26.paddingBottom = 2;
c26.paddingLeft = 6;
c26.primaryAxisSizingMode = 'AUTO';
c26.counterAxisSizingMode = 'AUTO';
c26.fills = [{ type: 'SOLID', color: hexToRgb('#F5F5FA') }];
c26.cornerRadius = 4;
var c27 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Bold' });
c27.fontName = { family: 'Inter', style: 'Bold' };
c27.fontSize = 10;
c27.characters = 'OPT';
c27.fills = [{ type: 'SOLID', color: hexToRgb('#888888') }];
c26.appendChild(c27);
c25.appendChild(c26);
var c28 = figma.createText();
await figma.loadFontAsync({ family: 'Fira Code', style: 'Regular' });
c28.fontName = { family: 'Fira Code', style: 'Regular' };
c28.fontSize = 12;
c28.characters = 'variant';
c28.fills = [{ type: 'SOLID', color: hexToRgb('#1A1A2E') }];
c28.resize(140, c28.height);
c28.textAutoResize = 'HEIGHT';
c25.appendChild(c28);
var c29 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });
c29.fontName = { family: 'Inter', style: 'Regular' };
c29.fontSize = 14;
c29.characters = 'enum';
c29.fills = [{ type: 'SOLID', color: hexToRgb('#C792EA') }];
c29.resize(100, c29.height);
c29.textAutoResize = 'HEIGHT';
c25.appendChild(c29);
var c30 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });
c30.fontName = { family: 'Inter', style: 'Regular' };
c30.fontSize = 14;
c30.characters = '"link"';
c30.fills = [{ type: 'SOLID', color: hexToRgb('#C3E88D') }];
c30.resize(120, c30.height);
c30.textAutoResize = 'HEIGHT';
c25.appendChild(c30);
var c31 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });
c31.fontName = { family: 'Inter', style: 'Regular' };
c31.fontSize = 14;
c31.characters = '"link" | "link-with-icon"';
c31.fills = [{ type: 'SOLID', color: hexToRgb('#1A1A2E') }];
c31.resize(200, c31.height);
c31.textAutoResize = 'HEIGHT';
c25.appendChild(c31);
var c32 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });
c32.fontName = { family: 'Inter', style: 'Regular' };
c32.fontSize = 14;
c32.characters = 'Link type with optional trailing icon';
c32.fills = [{ type: 'SOLID', color: hexToRgb('#595968') }];
c32.resize(350, c32.height);
c32.textAutoResize = 'HEIGHT';
c25.appendChild(c32);
c1.appendChild(c25);
_fillH(c25);
c25.layoutSizingVertical = 'HUG';
var c33 = figma.createFrame();
c33.name = 'Row 3';
c33.layoutMode = 'HORIZONTAL';
c33.itemSpacing = 0;
c33.paddingTop = 8;
c33.paddingRight = 12;
c33.paddingBottom = 8;
c33.paddingLeft = 12;
c33.primaryAxisSizingMode = 'AUTO';
c33.counterAxisSizingMode = 'AUTO';
c33.fills = [];
var c34 = figma.createFrame();
c34.name = 'OPT badge';
c34.layoutMode = 'HORIZONTAL';
c34.paddingTop = 2;
c34.paddingRight = 6;
c34.paddingBottom = 2;
c34.paddingLeft = 6;
c34.primaryAxisSizingMode = 'AUTO';
c34.counterAxisSizingMode = 'AUTO';
c34.fills = [{ type: 'SOLID', color: hexToRgb('#F5F5FA') }];
c34.cornerRadius = 4;
var c35 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Bold' });
c35.fontName = { family: 'Inter', style: 'Bold' };
c35.fontSize = 10;
c35.characters = 'OPT';
c35.fills = [{ type: 'SOLID', color: hexToRgb('#888888') }];
c34.appendChild(c35);
c33.appendChild(c34);
var c36 = figma.createText();
await figma.loadFontAsync({ family: 'Fira Code', style: 'Regular' });
c36.fontName = { family: 'Fira Code', style: 'Regular' };
c36.fontSize = 12;
c36.characters = 'external';
c36.fills = [{ type: 'SOLID', color: hexToRgb('#1A1A2E') }];
c36.resize(140, c36.height);
c36.textAutoResize = 'HEIGHT';
c33.appendChild(c36);
var c37 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });
c37.fontName = { family: 'Inter', style: 'Regular' };
c37.fontSize = 14;
c37.characters = 'boolean';
c37.fills = [{ type: 'SOLID', color: hexToRgb('#C792EA') }];
c37.resize(100, c37.height);
c37.textAutoResize = 'HEIGHT';
c33.appendChild(c37);
var c38 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });
c38.fontName = { family: 'Inter', style: 'Regular' };
c38.fontSize = 14;
c38.characters = 'false';
c38.fills = [{ type: 'SOLID', color: hexToRgb('#C3E88D') }];
c38.resize(120, c38.height);
c38.textAutoResize = 'HEIGHT';
c33.appendChild(c38);
var c39 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });
c39.fontName = { family: 'Inter', style: 'Regular' };
c39.fontSize = 14;
c39.characters = 'true | false';
c39.fills = [{ type: 'SOLID', color: hexToRgb('#1A1A2E') }];
c39.resize(200, c39.height);
c39.textAutoResize = 'HEIGHT';
c33.appendChild(c39);
var c40 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });
c40.fontName = { family: 'Inter', style: 'Regular' };
c40.fontSize = 14;
c40.characters = 'Opens in new tab with rel=noopener';
c40.fills = [{ type: 'SOLID', color: hexToRgb('#595968') }];
c40.resize(350, c40.height);
c40.textAutoResize = 'HEIGHT';
c33.appendChild(c40);
c1.appendChild(c33);
_fillH(c33);
c33.layoutSizingVertical = 'HUG';
var c41 = figma.createFrame();
c41.name = 'Row 4';
c41.layoutMode = 'HORIZONTAL';
c41.itemSpacing = 0;
c41.paddingTop = 8;
c41.paddingRight = 12;
c41.paddingBottom = 8;
c41.paddingLeft = 12;
c41.primaryAxisSizingMode = 'AUTO';
c41.counterAxisSizingMode = 'AUTO';
c41.fills = [];
var c42 = figma.createFrame();
c42.name = 'OPT badge';
c42.layoutMode = 'HORIZONTAL';
c42.paddingTop = 2;
c42.paddingRight = 6;
c42.paddingBottom = 2;
c42.paddingLeft = 6;
c42.primaryAxisSizingMode = 'AUTO';
c42.counterAxisSizingMode = 'AUTO';
c42.fills = [{ type: 'SOLID', color: hexToRgb('#F5F5FA') }];
c42.cornerRadius = 4;
var c43 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Bold' });
c43.fontName = { family: 'Inter', style: 'Bold' };
c43.fontSize = 10;
c43.characters = 'OPT';
c43.fills = [{ type: 'SOLID', color: hexToRgb('#888888') }];
c42.appendChild(c43);
c41.appendChild(c42);
var c44 = figma.createText();
await figma.loadFontAsync({ family: 'Fira Code', style: 'Regular' });
c44.fontName = { family: 'Fira Code', style: 'Regular' };
c44.fontSize = 12;
c44.characters = 'disabled';
c44.fills = [{ type: 'SOLID', color: hexToRgb('#1A1A2E') }];
c44.resize(140, c44.height);
c44.textAutoResize = 'HEIGHT';
c41.appendChild(c44);
var c45 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });
c45.fontName = { family: 'Inter', style: 'Regular' };
c45.fontSize = 14;
c45.characters = 'boolean';
c45.fills = [{ type: 'SOLID', color: hexToRgb('#C792EA') }];
c45.resize(100, c45.height);
c45.textAutoResize = 'HEIGHT';
c41.appendChild(c45);
var c46 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });
c46.fontName = { family: 'Inter', style: 'Regular' };
c46.fontSize = 14;
c46.characters = 'false';
c46.fills = [{ type: 'SOLID', color: hexToRgb('#C3E88D') }];
c46.resize(120, c46.height);
c46.textAutoResize = 'HEIGHT';
c41.appendChild(c46);
var c47 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });
c47.fontName = { family: 'Inter', style: 'Regular' };
c47.fontSize = 14;
c47.characters = 'true | false';
c47.fills = [{ type: 'SOLID', color: hexToRgb('#1A1A2E') }];
c47.resize(200, c47.height);
c47.textAutoResize = 'HEIGHT';
c41.appendChild(c47);
var c48 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });
c48.fontName = { family: 'Inter', style: 'Regular' };
c48.fontSize = 14;
c48.characters = 'Disables interaction, applies muted styling';
c48.fills = [{ type: 'SOLID', color: hexToRgb('#595968') }];
c48.resize(350, c48.height);
c48.textAutoResize = 'HEIGHT';
c41.appendChild(c48);
c1.appendChild(c41);
_fillH(c41);
c41.layoutSizingVertical = 'HUG';
var c49 = figma.createFrame();
c49.name = 'Row 5';
c49.layoutMode = 'HORIZONTAL';
c49.itemSpacing = 0;
c49.paddingTop = 8;
c49.paddingRight = 12;
c49.paddingBottom = 8;
c49.paddingLeft = 12;
c49.primaryAxisSizingMode = 'AUTO';
c49.counterAxisSizingMode = 'AUTO';
c49.fills = [];
var c50 = figma.createFrame();
c50.name = 'OPT badge';
c50.layoutMode = 'HORIZONTAL';
c50.paddingTop = 2;
c50.paddingRight = 6;
c50.paddingBottom = 2;
c50.paddingLeft = 6;
c50.primaryAxisSizingMode = 'AUTO';
c50.counterAxisSizingMode = 'AUTO';
c50.fills = [{ type: 'SOLID', color: hexToRgb('#F5F5FA') }];
c50.cornerRadius = 4;
var c51 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Bold' });
c51.fontName = { family: 'Inter', style: 'Bold' };
c51.fontSize = 10;
c51.characters = 'OPT';
c51.fills = [{ type: 'SOLID', color: hexToRgb('#888888') }];
c50.appendChild(c51);
c49.appendChild(c50);
var c52 = figma.createText();
await figma.loadFontAsync({ family: 'Fira Code', style: 'Regular' });
c52.fontName = { family: 'Fira Code', style: 'Regular' };
c52.fontSize = 12;
c52.characters = 'icon';
c52.fills = [{ type: 'SOLID', color: hexToRgb('#1A1A2E') }];
c52.resize(140, c52.height);
c52.textAutoResize = 'HEIGHT';
c49.appendChild(c52);
var c53 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });
c53.fontName = { family: 'Inter', style: 'Regular' };
c53.fontSize = 14;
c53.characters = 'ReactNode';
c53.fills = [{ type: 'SOLID', color: hexToRgb('#C792EA') }];
c53.resize(100, c53.height);
c53.textAutoResize = 'HEIGHT';
c49.appendChild(c53);
var c54 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });
c54.fontName = { family: 'Inter', style: 'Regular' };
c54.fontSize = 14;
c54.characters = '—';
c54.fills = [{ type: 'SOLID', color: hexToRgb('#C3E88D') }];
c54.resize(120, c54.height);
c54.textAutoResize = 'HEIGHT';
c49.appendChild(c54);
var c55 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });
c55.fontName = { family: 'Inter', style: 'Regular' };
c55.fontSize = 14;
c55.characters = 'icon element';
c55.fills = [{ type: 'SOLID', color: hexToRgb('#1A1A2E') }];
c55.resize(200, c55.height);
c55.textAutoResize = 'HEIGHT';
c49.appendChild(c55);
var c56 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });
c56.fontName = { family: 'Inter', style: 'Regular' };
c56.fontSize = 14;
c56.characters = 'Trailing icon (only when variant is link-with-icon)';
c56.fills = [{ type: 'SOLID', color: hexToRgb('#595968') }];
c56.resize(350, c56.height);
c56.textAutoResize = 'HEIGHT';
c49.appendChild(c56);
c1.appendChild(c49);
_fillH(c49);
c49.layoutSizingVertical = 'HUG';
var c57 = figma.createFrame();
c57.name = 'Row 6';
c57.layoutMode = 'HORIZONTAL';
c57.itemSpacing = 0;
c57.paddingTop = 8;
c57.paddingRight = 12;
c57.paddingBottom = 8;
c57.paddingLeft = 12;
c57.primaryAxisSizingMode = 'AUTO';
c57.counterAxisSizingMode = 'AUTO';
c57.fills = [];
var c58 = figma.createFrame();
c58.name = 'OPT badge';
c58.layoutMode = 'HORIZONTAL';
c58.paddingTop = 2;
c58.paddingRight = 6;
c58.paddingBottom = 2;
c58.paddingLeft = 6;
c58.primaryAxisSizingMode = 'AUTO';
c58.counterAxisSizingMode = 'AUTO';
c58.fills = [{ type: 'SOLID', color: hexToRgb('#F5F5FA') }];
c58.cornerRadius = 4;
var c59 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Bold' });
c59.fontName = { family: 'Inter', style: 'Bold' };
c59.fontSize = 10;
c59.characters = 'OPT';
c59.fills = [{ type: 'SOLID', color: hexToRgb('#888888') }];
c58.appendChild(c59);
c57.appendChild(c58);
var c60 = figma.createText();
await figma.loadFontAsync({ family: 'Fira Code', style: 'Regular' });
c60.fontName = { family: 'Fira Code', style: 'Regular' };
c60.fontSize = 12;
c60.characters = 'onClick';
c60.fills = [{ type: 'SOLID', color: hexToRgb('#1A1A2E') }];
c60.resize(140, c60.height);
c60.textAutoResize = 'HEIGHT';
c57.appendChild(c60);
var c61 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });
c61.fontName = { family: 'Inter', style: 'Regular' };
c61.fontSize = 14;
c61.characters = 'function';
c61.fills = [{ type: 'SOLID', color: hexToRgb('#C792EA') }];
c61.resize(100, c61.height);
c61.textAutoResize = 'HEIGHT';
c57.appendChild(c61);
var c62 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });
c62.fontName = { family: 'Inter', style: 'Regular' };
c62.fontSize = 14;
c62.characters = '—';
c62.fills = [{ type: 'SOLID', color: hexToRgb('#C3E88D') }];
c62.resize(120, c62.height);
c62.textAutoResize = 'HEIGHT';
c57.appendChild(c62);
var c63 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });
c63.fontName = { family: 'Inter', style: 'Regular' };
c63.fontSize = 14;
c63.characters = '(e) => void';
c63.fills = [{ type: 'SOLID', color: hexToRgb('#1A1A2E') }];
c63.resize(200, c63.height);
c63.textAutoResize = 'HEIGHT';
c57.appendChild(c63);
var c64 = figma.createText();
await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });
c64.fontName = { family: 'Inter', style: 'Regular' };
c64.fontSize = 14;
c64.characters = 'Click handler, fires before navigation';
c64.fills = [{ type: 'SOLID', color: hexToRgb('#595968') }];
c64.resize(350, c64.height);
c64.textAutoResize = 'HEIGHT';
c57.appendChild(c64);
c1.appendChild(c57);
_fillH(c57);
c57.layoutSizingVertical = 'HUG';
c0_slot.appendChild(c1);
_fillH(c1);
c1.layoutSizingVertical = 'HUG';
_wrapper.appendChild(c0);
_nodeCount++;

// Tag with plugin data
_wrapper.setSharedPluginData('actian_ds', 'skill', 'component-brief');
_wrapper.setSharedPluginData('actian_ds', 'pushed_at', new Date().toISOString());

// Return metadata
return { wrapperId: _wrapper.id, nodeCount: _nodeCount };